--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OguzhanUmutlu/Bosses
build-by-default: true
branches:
- main
projects:
  Bosses:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
...
