---
name: Bosses
version: 1.0.0
api: 3.0.0
main: OguzhanUmutlu\Bosses\Bosses

commands:
  boss:
    description: "Boss configuration command."
    permission: bosses.cmd

permissions:
  bosses.cmd:
    default: op
...